# eralyzer.py — multi-agent era classifier (Streamlit frontend)
#
# All debate data is generated by real agents at runtime.
# eralyzer-data.js (static placeholder) is NOT used.
#
# Run:  streamlit run eralyzer.py

import json
import pickle
import re
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import streamlit as st

BASE = Path(__file__).parent
sys.path.insert(0, str(BASE))

# ── Page config ───────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="eralyzer — multi-agent taylor swift era classifier",
    page_icon="🎶",
    layout="wide",
    initial_sidebar_state="collapsed",
)
st.markdown("""
<style>
  header[data-testid="stHeader"]              { display:none; }
  div[data-testid="stToolbar"]                { display:none; }
  footer                                       { display:none; }
  .block-container                            { padding:0 !important; max-width:100% !important; }
  [data-testid="stAppViewContainer"] > .main { padding:0 !important; }
</style>
""", unsafe_allow_html=True)

# ── Constants ─────────────────────────────────────────────────────────────────
ERAS_META = {
    "Taylor Swift": {"id": "debut",     "label": "Debut",      "year": 2006, "color": "#c8a97e"},
    "Fearless":     {"id": "fearless",  "label": "Fearless",   "year": 2008, "color": "#d9a818"},
    "Speak Now":    {"id": "speaknow",  "label": "Speak Now",  "year": 2010, "color": "#9a6cc1"},
    "Red":          {"id": "red",       "label": "Red",        "year": 2012, "color": "#b53030"},
    "1989":         {"id": "1989",      "label": "1989",       "year": 2014, "color": "#4a9fc7"},
    "Reputation":   {"id": "rep",       "label": "Reputation", "year": 2017, "color": "#4a4a4a"},
    "Lover":        {"id": "lover",     "label": "Lover",      "year": 2019, "color": "#db83b0"},
    "Folklore":     {"id": "folklore",  "label": "Folklore",   "year": 2020, "color": "#6f8a5c"},
    "Evermore":     {"id": "evermore",  "label": "Evermore",   "year": 2020, "color": "#b56830"},
    "Midnights":    {"id": "midnights", "label": "Midnights",  "year": 2022, "color": "#4a5aa8"},
}
ERA_ORDER = [
    "Taylor Swift", "Fearless", "Speak Now", "Red", "1989",
    "Reputation", "Lover", "Folklore", "Evermore", "Midnights",
]

# ── Cached resource loaders ───────────────────────────────────────────────────
@st.cache_data
def get_confusion_matrix_data():
    """Return a 6×6 confusion matrix (list of lists) from the real model + test set."""
    try:
        from src.preprocessing import TextPreprocessor
        from sklearn.metrics import confusion_matrix

        model_path = BASE / "model.pkl"
        test_path  = BASE / "data" / "processed" / "test_dataset.csv"
        if not model_path.exists() or not test_path.exists():
            return None, None

        with open(model_path, "rb") as f:
            model = pickle.load(f)

        df = pd.read_csv(test_path)
        preprocessor = TextPreprocessor()
        df["clean_lyrics"], sentiments = preprocessor.transform_with_features(df["lyrics"].tolist())
        df = pd.concat([df, pd.DataFrame(sentiments, index=df.index)], axis=1)

        # Feature engineering (matches train.py)
        df["acoustic_energy_ratio"]  = df["acousticness"] / (df["energy"] + 0.001)
        df["dance_valence_product"]  = df["danceability"] * df["valence"]
        df["loudness_norm"]          = (df["loudness"] + 60) / 60
        df["tempo_bin"] = pd.cut(
            df["tempo"], bins=[0,90,110,130,160,250], labels=[0,1,2,3,4]
        ).astype(float)
        df["speech_acoustic_diff"]   = df["speechiness"] - df["acousticness"]
        for k in range(12):
            if f"key_{k}" not in df.columns: df[f"key_{k}"] = (df["key"] == k).astype(float)
        for m in [0,1]:
            if f"mode_{m}" not in df.columns: df[f"mode_{m}"] = (df["mode"] == m).astype(float)

        audio_cols = [
            "danceability","energy","loudness","speechiness",
            "acousticness","instrumentalness","liveness","valence",
            "tempo","duration_ms",
            "acoustic_energy_ratio","dance_valence_product","loudness_norm",
            "tempo_bin","speech_acoustic_diff",
            "compound","pos","neg","neu",
        ] + [f"key_{i}" for i in range(12)] + [f"mode_{i}" for i in range(2)]

        X_audio = df[audio_cols].values
        X_text  = df["clean_lyrics"].to_numpy(dtype=str)
        y_true  = df["era"].to_numpy(dtype=str)

        y_pred = model.predict(X_audio, X_text)
        cm = confusion_matrix(y_true, y_pred, labels=ERA_ORDER)
        # Normalise rows → fractions
        row_sums = cm.sum(axis=1, keepdims=True).clip(min=1)
        cm_norm  = (cm / row_sums).tolist()
        return cm_norm, ERA_ORDER

    except Exception as e:
        return None, None

cm_data, cm_labels = get_confusion_matrix_data()

# ── Build the JS data block ────────────────────────────────────────────────────
def make_data_js() -> str:
    eras_list = list(ERAS_META.values())
    # DEMOS: one per era, all confirmed in the merged 224-song dataset
    demos_list = [
        {"era": "debut",     "title": "Tim McGraw",         "artist": "Taylor Swift"},
        {"era": "fearless",  "title": "Love Story",         "artist": "Taylor Swift"},
        {"era": "speaknow",  "title": "Enchanted",          "artist": "Taylor Swift"},
        {"era": "red",       "title": "All Too Well",       "artist": "Taylor Swift"},
        {"era": "1989",      "title": "Blank Space",        "artist": "Taylor Swift"},
        {"era": "rep",       "title": "Getaway Car",        "artist": "Taylor Swift"},
        {"era": "lover",     "title": "Cruel Summer",       "artist": "Taylor Swift"},
        {"era": "folklore",  "title": "cardigan",           "artist": "Taylor Swift"},
        {"era": "evermore",  "title": "champagne problems", "artist": "Taylor Swift"},
        {"era": "midnights", "title": "Lavender Haze",      "artist": "Taylor Swift"},
    ]

    # Confusion matrix
    if cm_data and cm_labels:
        confusion_js = json.dumps(cm_data)
        labels_js    = json.dumps([ERAS_META[l]["label"] for l in cm_labels])
        matrix_note  = "Hold-out test set · text agent · real model predictions"
    else:
        confusion_js = "null"
        labels_js    = json.dumps([e["label"] for e in eras_list])
        matrix_note  = "Run python train.py to generate confusion matrix data"

    return f"""
const ERAS = {json.dumps(eras_list)};
const DEMOS = {json.dumps(demos_list)};

// Confusion matrix — {matrix_note}
const _RAW_CM    = {confusion_js};
const _CM_LABELS = {labels_js};
const CONFUSION  = _RAW_CM;   // may be null — matrix section handles gracefully

// API base URL — eralyzer.js uses this when served inside the Streamlit iframe
const DEBATE_API_BASE = "http://localhost:8000";
"""

# ── Bundle HTML: eralyzer.html + eralyzer.css + real data JS + eralyzer.js ────
def bundle_html() -> str:
    html = (BASE / "eralyzer.html").read_text(encoding="utf-8")
    css  = (BASE / "eralyzer.css").read_text(encoding="utf-8")
    js   = (BASE / "eralyzer.js").read_text(encoding="utf-8")
    data = make_data_js()

    # Patch the matrix section to handle null CONFUSION gracefully
    js = js.replace(
        "buildMatrix();",
        """if (typeof CONFUSION !== 'undefined' && CONFUSION !== null) {
  buildMatrix();
} else {
  const w = document.getElementById('matrix');
  if (w) w.innerHTML = '<div style="font-family:var(--font-mono);font-size:12px;'
    + 'color:var(--ink-3);padding:24px;">Train the model first to see the real confusion matrix.</div>';
}"""
    )

    html = html.replace(
        '<link rel="stylesheet" href="eralyzer.css" />',
        f"<style>\n{css}\n</style>"
    )
    # Replace eralyzer-data.js with real agent data
    html = html.replace(
        '<script src="eralyzer-data.js"></script>',
        f"<script>\n{data}\n</script>"
    )
    html = html.replace(
        '<script src="eralyzer.js"></script>',
        f"<script>\n{js}\n</script>"
    )
    return html

# ── Render the eralyzer UI (no Streamlit widget — input lives inside the HTML) ─
# NOTE: prefer running FastAPI directly:  uvicorn api:app --reload  → localhost:8000
# This Streamlit wrapper is kept as a legacy convenience; it forwards /debate
# calls to the FastAPI server at localhost:8000 via the injected DEBATE_API_BASE.

html = bundle_html()
st.components.v1.html(html, height=2400, scrolling=True)
