# eralyzer.py — multi-agent era classifier (Streamlit frontend)
#
# All debate data is generated by real agents at runtime.
# eralyzer-data.js (static placeholder) is NOT used.
#
# Run:  streamlit run eralyzer.py

import json
import os
import pickle
import re
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import streamlit as st
from dotenv import load_dotenv

load_dotenv()

BASE = Path(__file__).parent
sys.path.insert(0, str(BASE))

# ── Page config ───────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="eralyzer — multi-agent taylor swift era classifier",
    page_icon="🎶",
    layout="wide",
    initial_sidebar_state="collapsed",
)
st.markdown("""
<style>
  header[data-testid="stHeader"]              { display:none; }
  div[data-testid="stToolbar"]                { display:none; }
  footer                                       { display:none; }
  .block-container                            { padding:0 !important; max-width:100% !important; }
  [data-testid="stAppViewContainer"] > .main { padding:0 !important; }
</style>
""", unsafe_allow_html=True)

# ── Constants ─────────────────────────────────────────────────────────────────
ERAS_META = {
    "Taylor Swift": {"id": "debut",     "label": "Debut",      "year": 2006, "color": "#c8a97e"},
    "Fearless":     {"id": "fearless",  "label": "Fearless",   "year": 2008, "color": "#d9a818"},
    "Speak Now":    {"id": "speaknow",  "label": "Speak Now",  "year": 2010, "color": "#9a6cc1"},
    "Red":          {"id": "red",       "label": "Red",        "year": 2012, "color": "#b53030"},
    "1989":         {"id": "1989",      "label": "1989",       "year": 2014, "color": "#4a9fc7"},
    "Reputation":   {"id": "rep",       "label": "Reputation", "year": 2017, "color": "#4a4a4a"},
    "Lover":        {"id": "lover",     "label": "Lover",      "year": 2019, "color": "#db83b0"},
    "Folklore":     {"id": "folklore",  "label": "Folklore",   "year": 2020, "color": "#6f8a5c"},
    "Evermore":     {"id": "evermore",  "label": "Evermore",   "year": 2020, "color": "#b56830"},
    "Midnights":    {"id": "midnights", "label": "Midnights",  "year": 2022, "color": "#4a5aa8"},
}
ERA_ORDER = [
    "Taylor Swift", "Fearless", "Speak Now", "Red", "1989",
    "Reputation", "Lover", "Folklore", "Evermore", "Midnights",
]

# ── Cached resource loaders ───────────────────────────────────────────────────
_ALBUM_ERA = {
    "Taylor Swift":                        "Taylor Swift",
    "Beautiful Eyes":                      "Taylor Swift",
    "The Taylor Swift Holiday Collection": "Taylor Swift",
    "Fearless":                            "Fearless",
    "Fearless (Taylor's Version)":         "Fearless",
    "Speak Now":                           "Speak Now",
    "Red":                                 "Red",
    "Red (Taylor's Version)":              "Red",
    "1989":                                "1989",
    "reputation":                          "Reputation",
    "Lover":                               "Lover",
    "folklore":                            "Folklore",
}
_TV_ALBUMS = {"Fearless (Taylor's Version)", "Red (Taylor's Version)"}
_ERA_ORDER_8 = ["Taylor Swift", "Fearless", "Speak Now", "Red", "1989", "Reputation", "Lover", "Folklore"]

def _load_lyric_testset():
    """Return the held-out lyrics test DataFrame (same split as train_text_agent.py)."""
    from sklearn.model_selection import train_test_split
    csv_path = BASE / "TaylorSwiftEras" / "Data" / "Final" / "taylor_merged_df.csv"
    df = pd.read_csv(csv_path)
    original_titles = set(
        df.loc[~df["album_name"].isin(_TV_ALBUMS), "track_name"].str.lower().str.strip()
    )
    df = df[
        ~df["album_name"].isin(_TV_ALBUMS) |
        ~df["track_name"].str.lower().str.strip().isin(original_titles)
    ].copy()
    df["era"]    = df["album_name"].map(_ALBUM_ERA)
    df["lyrics"] = df["lyric"]
    df = df.dropna(subset=["era", "lyrics"])
    df = df[df["lyrics"].str.strip() != ""].reset_index(drop=True)
    _, df_test = train_test_split(df, test_size=0.2, random_state=42, stratify=df["era"])
    return df_test

def _load_audio_testset():
    """Return the held-out audio test DataFrame (same split as train_audio_agent.py)."""
    from sklearn.model_selection import train_test_split
    csv_path = BASE / "TaylorSwiftEras" / "Data" / "Final" / "taylor_merged_df.csv"
    df = pd.read_csv(csv_path)
    original_titles = set(
        df.loc[~df["album_name"].isin(_TV_ALBUMS), "track_name"].str.lower().str.strip()
    )
    df = df[
        ~df["album_name"].isin(_TV_ALBUMS) |
        ~df["track_name"].str.lower().str.strip().isin(original_titles)
    ].copy()
    df["era"] = df["album_name"].map(_ALBUM_ERA)
    df = df.dropna(subset=["era"]).reset_index(drop=True)
    _, df_test = train_test_split(df, test_size=0.2, random_state=42, stratify=df["era"])
    return df_test

@st.cache_data
def get_text_confusion_matrix_data():
    """Return normalised 8×8 confusion matrix from the TextAgent on its held-out test set."""
    try:
        from sklearn.metrics import confusion_matrix
        from src.text_agent import TextAgent
        model_path = BASE / "models" / "text_agent.pkl"
        if not model_path.exists():
            return None, None
        agent   = TextAgent.load(str(model_path))
        df_test = _load_lyric_testset()
        y_true, y_pred = [], []
        for _, row in df_test.iterrows():
            result = agent.predict_with_evidence(row["lyrics"], use_llm=False)
            y_true.append(row["era"])
            y_pred.append(result["predicted_era"])
        cm = confusion_matrix(y_true, y_pred, labels=_ERA_ORDER_8)
        row_sums = cm.sum(axis=1, keepdims=True).clip(min=1)
        return (cm / row_sums).tolist(), _ERA_ORDER_8
    except Exception:
        return None, None

@st.cache_data
def get_audio_confusion_matrix_data():
    """Return normalised 8×8 confusion matrix from the AudioAgent on its held-out test set."""
    try:
        from sklearn.metrics import confusion_matrix
        from src.audio_agent import AudioAgent
        model_path = BASE / "models" / "audio_agent.pkl"
        if not model_path.exists():
            return None, None
        agent   = AudioAgent.load(str(model_path))
        df_test = _load_audio_testset()
        y_true, y_pred = [], []
        for _, row in df_test.iterrows():
            result = agent.predict_with_evidence(row.to_dict(), use_llm=False)
            y_true.append(row["era"])
            y_pred.append(result["predicted_era"])
        cm = confusion_matrix(y_true, y_pred, labels=_ERA_ORDER_8)
        row_sums = cm.sum(axis=1, keepdims=True).clip(min=1)
        return (cm / row_sums).tolist(), _ERA_ORDER_8
    except Exception:
        return None, None

cm_text_data,  cm_text_labels  = get_text_confusion_matrix_data()
cm_audio_data, cm_audio_labels = get_audio_confusion_matrix_data()

# ── Build the JS data block ────────────────────────────────────────────────────
def make_data_js() -> str:
    eras_list = list(ERAS_META.values())
    # DEMOS: one per era, all confirmed in the merged 224-song dataset
    demos_list = [
        {"era": "debut",     "title": "Tim McGraw",         "artist": "Taylor Swift"},
        {"era": "fearless",  "title": "Love Story",         "artist": "Taylor Swift"},
        {"era": "speaknow",  "title": "Enchanted",          "artist": "Taylor Swift"},
        {"era": "red",       "title": "All Too Well",       "artist": "Taylor Swift"},
        {"era": "1989",      "title": "Blank Space",        "artist": "Taylor Swift"},
        {"era": "rep",       "title": "Getaway Car",        "artist": "Taylor Swift"},
        {"era": "lover",     "title": "Cruel Summer",       "artist": "Taylor Swift"},
        {"era": "folklore",  "title": "cardigan",           "artist": "Taylor Swift"},
        {"era": "evermore",  "title": "champagne problems", "artist": "Taylor Swift"},
        {"era": "midnights", "title": "Lavender Haze",      "artist": "Taylor Swift"},
    ]

    cm8_labels_js = json.dumps(_ERA_ORDER_8)
    confusion_text_js  = json.dumps(cm_text_data)  if cm_text_data  else "null"
    confusion_audio_js = json.dumps(cm_audio_data) if cm_audio_data else "null"

    return f"""
const ERAS = {json.dumps(eras_list)};
const DEMOS = {json.dumps(demos_list)};

// Confusion matrices — hold-out test set (random_state=42), row-normalised fractions
const CM_LABELS      = {cm8_labels_js};
const CONFUSION_TEXT  = {confusion_text_js};
const CONFUSION_AUDIO = {confusion_audio_js};

// API base URL — eralyzer.js uses this when served inside the Streamlit iframe
const DEBATE_API_BASE = "{os.getenv('DEBATE_API_BASE', 'http://localhost:8002')}";
"""

# ── Bundle HTML: eralyzer.html + eralyzer.css + real data JS + eralyzer.js ────
def bundle_html() -> str:
    html = (BASE / "eralyzer.html").read_text(encoding="utf-8")
    css  = (BASE / "eralyzer.css").read_text(encoding="utf-8")
    js   = (BASE / "eralyzer.js").read_text(encoding="utf-8")
    data = make_data_js()

    html = html.replace(
        '<link rel="stylesheet" href="eralyzer.css" />',
        f"<style>\n{css}\n</style>"
    )
    # Replace eralyzer-data.js with real agent data
    html = html.replace(
        '<script src="eralyzer-data.js"></script>',
        f"<script>\n{data}\n</script>"
    )
    html = html.replace(
        '<script src="eralyzer.js"></script>',
        f"<script>\n{js}\n</script>"
    )
    return html

# ── Render the eralyzer UI (no Streamlit widget — input lives inside the HTML) ─
# NOTE: prefer running FastAPI directly:  uvicorn api:app --reload  → localhost:8000
# This Streamlit wrapper is kept as a legacy convenience; it forwards /debate
# calls to the FastAPI server at localhost:8000 via the injected DEBATE_API_BASE.

html = bundle_html()
st.components.v1.html(html, height=2400, scrolling=True)
